DB_URL = "https://docs.google.com/spreadsheets/d/1o3_pxe9VcjFJGCtRoqLw6Npfhwj1ZNzCe-W_ru3SNVM/edit?usp=sharing"

#private_gsheets_url = "https://docs.google.com/spreadsheets/d/1o3_pxe9VcjFJGCtRoqLw6Npfhwj1ZNzCe-W_ru3SNVM/edit?usp=sharing"

#[
#gcp_service_account
#]
#type = "service_account"
#project_id = "133952709382"
#private_key_id = "110063924654276269132"
#private_key = "133952709382"
#client_email = "thiago@qr-code-streamlit.iam.gserviceaccount.com"
#client_id = "110063924654276269132"
#auth_uri = "https://accounts.google.com/o/oauth2/auth"
#token_uri = "https://oauth2.googleapis.com/token"
#auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"

